[package]
name = "experimenting2"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"


[dependencies]
async-std = { version = "1.9", features = ["attributes"] }
async-trait = "0.1"
once_cell = "1.7"