[package]
name = "rstream"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"

typemap = "0.3"

rand = "0.8"

derivative = "2.2"

serde = { version="1.0", features = ["derive"] }
serde_yaml = "0.8"
bincode = "1.3"

anyhow = "1.0"

itertools = "0.10"

lazy_static = "1.4"

ssh2 = { version = "0.9", features = ["vendored-openssl"] }
whoami = "1.1"
shell-escape = "0.1"

structopt = "0.3"

[dev-dependencies]
# for the tests
tempfile = "3.2"
criterion = { version = "0.3", features = ["html_reports"] }
fake = "2.4"

# for the examples
regex = "1.4.3"

[[bench]]
name = "wordcount"
harness = false

[[bench]]
name = "shuffle"
harness = false

[[bench]]
name = "fold_vs_reduce"
harness = false

[[bench]]
name = "batch_mode"
harness = false

[profile.release]
debug = true