name: Docs

on:
  push:
    branches:
      - 'master'

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --color=always --no-deps --all
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages
          folder: target/doc
