name: Docs

on:
  push:
    branches:
      - 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo Doc
        run: cargo doc --verbose --color=always --no-deps --all
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          branch: gh-pages
          path: target/doc
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
