name: Rust

on: [push, pull_request]

env:
  RUST_BACKTRACE: full
  RUST_LOG: debug

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --tests --all -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        timeout-minutes: 20
        env:
          RSTREAM_TEST_LOCAL_CORES: 1,2,4,8
          RSTREAM_TEST_REMOTE_HOSTS: 1,2,4
          RSTREAM_TEST_REMOTE_CORES: 1,2,4,8
          RSTREAM_TEST_TIMEOUT: 10
        with:
          command: test
          args: --all

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        id: component
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check